[package]
name = "log_redactor"
version = "0.1.0"
authors = ["Author Name <author@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
regex = "1.5.4"
serde_json = "1.0.64"
zip = "0.5.13"
