name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-audit if needed
        run: |
          if ! command -v cargo-audit &> /dev/null; then
            cargo install cargo-audit
          fi
      - name: Audit dependencies
        run: cargo audit
        continue-on-error: true
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
        continue-on-error: true
      - name: Lint with clippy
        run: cargo clippy -- -D warnings
